### ISSUE TITLE
phpBB3 ver 3.1

### ISSUE THREAD

**Issue by federicovilla** [bluegaurav/phpbb-integration-in-codeigniter#1]
Hallo,
finally I found what I was looking for.
I'd like to integrate phpBB 3 into my web site ( login, user registration and so on ... )
I'm wondering if your library work fines with latest phpBB, the 3.1.6 version.
May I ask some info about how install this library?
Thanks a lot

**Comment by bluegaurav** [comment]
what is the name of  Framwrok which you have used in your website ?

**Comment by GliderHacker** [comment]
Hallo...thanks a lot for reply;
I'm developing the new web site in Codeigniter 3.
Thanks for any feedback 
Federico

Inviato da iPhone
